-- Generated by leo3-codegen. Do not edit.
-- Class: Account

opaque Account.ffi : NonemptyType
def Account : Type := Account.ffi.val
instance : Nonempty Account := Account.ffi.property

@[extern "__lean_ffi_Account_new"] opaque Account.new : String → Account
@[extern "__lean_ffi_Account_balance"] opaque Account.balance : Account → Int64
@[extern "__lean_ffi_Account_owner"] opaque Account.owner : Account → String
@[extern "__lean_ffi_Account_set_balance"] opaque Account.set_balance : Account → Int64 → Account
@[extern "__lean_ffi_Account_deposit"] opaque Account.deposit : Account → Int64 → Account
@[extern "__lean_ffi_Account_withdraw"] opaque Account.withdraw : Account → Int64 → Prod Account Bool
@[extern "__lean_ffi_Account_describe"] opaque Account.describe : Account → String
