//! Classification of Rust scalar types that cross the Lean FFI boundary
//! unboxed.
//!
//! Lean compiles `@[extern] opaque` declarations with an unboxed calling
//! convention for its fixed-width scalar types: a declaration such as
//! `UInt64 → Int32` calls the C symbol with a raw `uint64_t` argument and
//! expects a raw `uint32_t` result. Only non-scalar shapes (`String`,
//! `Array`, `Option`, `Except`, `Prod`, external class objects, ...) are
//! passed as boxed `lean_object*` values.
//!
//! The wrappers generated by `#[leanfn]` and `#[leanclass]` must match this
//! convention exactly, so scalar parameters and results bypass the
//! `FromLean` / `IntoLean` object machinery entirely.

use proc_macro2::TokenStream;
use quote::quote;

/// A Rust scalar type with an unboxed Lean FFI representation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ScalarAbi {
    U8,
    U16,
    U32,
    U64,
    USize,
    I8,
    I16,
    I32,
    I64,
    ISize,
    F32,
    F64,
    Bool,
    Char,
}

impl ScalarAbi {
    /// Classify a Rust type as an unboxed FFI scalar, if it is one.
    ///
    /// Only plain path types (`u64`, `bool`, ...) qualify; references,
    /// containers and named types all use the boxed object convention.
    pub fn from_type(ty: &syn::Type) -> Option<Self> {
        let syn::Type::Path(type_path) = ty else {
            return None;
        };
        if type_path.qself.is_some() {
            return None;
        }
        let segment = type_path.path.segments.last()?;
        if !segment.arguments.is_empty() {
            return None;
        }
        match segment.ident.to_string().as_str() {
            "u8" => Some(Self::U8),
            "u16" => Some(Self::U16),
            "u32" => Some(Self::U32),
            "u64" => Some(Self::U64),
            "usize" => Some(Self::USize),
            "i8" => Some(Self::I8),
            "i16" => Some(Self::I16),
            "i32" => Some(Self::I32),
            "i64" => Some(Self::I64),
            "isize" => Some(Self::ISize),
            "f32" => Some(Self::F32),
            "f64" => Some(Self::F64),
            "bool" => Some(Self::Bool),
            "char" => Some(Self::Char),
            _ => None,
        }
    }

    /// The C-ABI boundary type used in generated `extern "C"` signatures.
    ///
    /// Numeric scalars keep their Rust type (identical ABI); `bool` crosses
    /// as `u8` and `char` as `u32`, matching the `uint8_t` / `uint32_t`
    /// prototypes Lean emits for `Bool` and `Char`.
    pub fn boundary_type(self) -> TokenStream {
        match self {
            Self::U8 => quote! { u8 },
            Self::U16 => quote! { u16 },
            Self::U32 => quote! { u32 },
            Self::U64 => quote! { u64 },
            Self::USize => quote! { usize },
            Self::I8 => quote! { i8 },
            Self::I16 => quote! { i16 },
            Self::I32 => quote! { i32 },
            Self::I64 => quote! { i64 },
            Self::ISize => quote! { isize },
            Self::F32 => quote! { f32 },
            Self::F64 => quote! { f64 },
            Self::Bool => quote! { u8 },
            Self::Char => quote! { u32 },
        }
    }

    /// Statement binding the Rust parameter `name` from the boundary argument
    /// `arg`. Numeric scalars pass through unchanged; `bool` and `char` are
    /// reconstructed from their boundary representation (`char` rejects
    /// invalid code points through the enclosing `LeanResult`).
    pub fn param_binding(
        self,
        name: &syn::Ident,
        arg: &syn::Ident,
        leo3_crate: &TokenStream,
    ) -> TokenStream {
        match self {
            Self::Bool => quote! {
                let #name = #arg != 0;
            },
            Self::Char => quote! {
                let #name = ::core::char::from_u32(#arg).ok_or_else(|| {
                    #leo3_crate::LeanError::conversion(&format!(
                        "Failed to convert `{}` from Lean to Rust: invalid Char code point {}",
                        stringify!(#name),
                        #arg
                    ))
                })?;
            },
            _ => quote! {
                let #name = #arg;
            },
        }
    }

    /// Expression converting the Rust result `value` into the boundary
    /// representation returned to Lean.
    pub fn result_expr(self, value: TokenStream) -> TokenStream {
        match self {
            Self::Bool => quote! { u8::from(#value) },
            Self::Char => quote! { #value as u32 },
            _ => value,
        }
    }
}
