-- Generated by leo3-codegen. Do not edit.
-- Module: ClassIntegration.Native

@[extern "ci_add"] opaque ci_add : UInt64 → UInt64 → UInt64

@[extern "ci_banner"] opaque ci_banner : String → Int32 → String

@[extern "ci_sum"] opaque ci_sum : Array UInt64 → UInt64

